[package]
name = "oxc_semantic_napi"
version = "0.151.0"
edition = "2021"
publish = false
build = "src/rs/build.rs"

[lib]
path = "src/rs/lib.rs"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi9"] }
napi-derive = "3"
oxc_allocator = "0.151.0"
oxc_ast_visit = { version = "0.151.0", features = ["serialize"] }
oxc_diagnostics = "0.151.0"
oxc_index = "5.0.0"
oxc_parser = "0.151.0"
oxc_semantic = "0.151.0"
oxc_span = "0.151.0"
oxc_syntax = "0.151.0"

[build-dependencies]
napi-build = "2"
